/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TimeSync {
    uint32_t year; /* 年份，范围 0 - 65535 */
    uint32_t month; /* 月份，范围 1 - 12 */
    uint32_t day; /* 日期，范围 1 - 31 */
    uint32_t hour; /* 小时，范围 0 - 23 */
    uint32_t minute; /* 分钟，范围 0 - 59 */
    uint32_t second; /* 秒，范围 0 - 60 */
} TimeSync;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TimeSync_init_default                    {0, 0, 0, 0, 0, 0}
#define TimeSync_init_zero                       {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TimeSync_year_tag                        1
#define TimeSync_month_tag                       2
#define TimeSync_day_tag                         3
#define TimeSync_hour_tag                        4
#define TimeSync_minute_tag                      5
#define TimeSync_second_tag                      6

/* Struct field encoding specification for nanopb */
#define TimeSync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   year,              1) \
X(a, STATIC,   SINGULAR, UINT32,   month,             2) \
X(a, STATIC,   SINGULAR, UINT32,   day,               3) \
X(a, STATIC,   SINGULAR, UINT32,   hour,              4) \
X(a, STATIC,   SINGULAR, UINT32,   minute,            5) \
X(a, STATIC,   SINGULAR, UINT32,   second,            6)
#define TimeSync_CALLBACK NULL
#define TimeSync_DEFAULT NULL

extern const pb_msgdesc_t TimeSync_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TimeSync_fields &TimeSync_msg

/* Maximum encoded size of messages (where known) */
#define MESSAGE_PB_H_MAX_SIZE                    TimeSync_size
#define TimeSync_size                            36

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
